routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('css/{filename}', 'AssetsController@css')->where('filename', '(.*)')->name('assets.css');
Route::get('js/{filename}', 'AssetsController@js')->where('filename', '(.*)')->name('assets.js');
Route::get('fonts/{filename}', 'AssetsController@fonts')->where('filename', '(.*)')->name('assets.fonts');

Route::middleware('auth')->group(function() {
    Route::get('home', 'HomeController@index')->name('home');

    Route::get('palimpsest/record/{palimpsest}/{record}', 'PalimpsestController@record')->name('palimpsest.record');
    Route::post('palimpsest/records/{palimpsest}', 'PalimpsestController@handleRecords')->name('palimpsest.records');
    Route::post('palimpsest/loopback/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@loopback')->name('palimpsest.loopback');
    Route::post('palimpsest/broadcast/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@broadcast')->name('palimpsest.broadcast');
    Route::get('palimpsest/askremove/{palimpsest}', 'PalimpsestController@askRemove')->name('palimpsest.ask_remove');

    Route::get('record/askremove/{record:identifier}', 'RecordController@askRemove')->name('record.ask_remove');

    Route::resource('record', 'RecordController');
    Route::resource('palimpsest', 'PalimpsestController');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row mb-5">
        <div class="col-md-12">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#edit-record-new">Create New Record</a>
            @include('record.edit', ['record' => null])

            <a href="{{ route('palimpsest.index') }}" class="btn btn-secondary">Go to Palimpsest View</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Latest Records</div>

                <div class="card-body">
                    @if($user->records()->count() == 0)
                        <div class="alert alert-info">
                            There are no records.
                        </div>
                    @else
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Identifier</th>
                                    <th>URL</th>
                                    <th>Created At</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($user->records()->take(10)->get() as $record)
                                    <tr>
                                        <td>{{ $record->identifier }}</td>
                                        <td>{{ $record->url }}</td>
                                        <td>{{ $record->created_at }}</td>
                                        <td>
                                            @if($record->status == 'running')
                                                <a href="{{ route('record.stop', ['id' => $record->id, 'api_key' => $user->api_key]) }}" class="btn btn-danger reload_on_click">Stop Record</a>
                                            @endif

                                            <a href="#" class="btn btn-danger remote-modal" data-modal-url="{{ route('record.ask_remove', $record->identifier) }}">Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection