routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('css/{filename}', 'AssetsController@css')->where('filename', '(.*)')->name('assets.css');
Route::get('js/{filename}', 'AssetsController@js')->where('filename', '(.*)')->name('assets.js');
Route::get('fonts/{filename}', 'AssetsController@fonts')->where('filename', '(.*)')->name('assets.fonts');

Route::middleware('auth')->group(function() {
    Route::get('home', 'HomeController@index')->name('home');

    Route::get('palimpsest/record/{palimpsest}/{record}', 'PalimpsestController@record')->name('palimpsest.record');
    Route::post('palimpsest/records/{palimpsest}', 'PalimpsestController@handleRecords')->name('palimpsest.records');
    Route::post('palimpsest/loopback/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@loopback')->name('palimpsest.loopback');
    Route::post('palimpsest/broadcast/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@broadcast')->name('palimpsest.broadcast');
    Route::get('palimpsest/askremove/{palimpsest}', 'PalimpsestController@askRemove')->name('palimpsest.ask_remove');

    Route::get('record/askremove/{record:identifier}', 'RecordController@askRemove')->name('record.ask_remove');

    Route::resource('record', 'RecordController');
    Route::resource('palimpsest', 'PalimpsestController');
});

app/Palimpsest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Log;

class Palimpsest extends Model
{
    public function subConfig($name)
    {
        $obj = json_decode($this->config);
        return $obj->$name ?? '';
    }

    public function records()
    {
        return $this->belongsToMany('App\Record')->withPivot(['sorting', 'notes'])->orderBy('sorting', 'asc');
    }

    public function broadcast($record)
    {
        $palimpsest = $this;
        $already_broadcasting = false;
        $already_in_palimpsest = false;

        foreach($this->records as $r) {
            if ($r->id == $record->id) {
                $already_in_palimpsest = true;
            }

            $destinations = $r->destinations()->where(function($query) use ($palimpsest) {
                $query->where('driver', $palimpsest->driver)->where('config', $palimpsest->subConfig('sendto'));
            })->get();

            if ($destinations->isEmpty() == false) {
                if ($r->id == $record->id) {
                    $already_broadcasting = true;
                    Log::info('Already broadcasting');
                }
                else {
                    foreach($destinations as $d) {
                        $d->delete();
                    }

                    $r->reroute();
                }
            }
        }

        if (!$already_broadcasting) {
            $dest = new Destination();
            $dest->driver = $palimpsest->driver;
            $dest->config = $palimpsest->subConfig('sendto');
            $dest->record_id = $record->id;
            $dest->save();

            $record->reroute();
        }

        if ($already_in_palimpsest == false) {
            $this->records()->attach($record->id);
        }
    }
}

app/Http/Controllers/PalimpsestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Palimpsest;
use App\Record;
use App\Destination;

class PalimpsestController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $user->refresh();
        return view('palimpsest.index', compact('user'));
    }

    private function readRequest($palimpsest, $request)
    {
        $palimpsest->name = $request->input('name');
        $palimpsest->driver = $request->input('driver');

        $config = (object) [];

        foreach(Destination::drivers() as $driver) {
            if ($driver->identifier == $palimpsest->driver) {
                foreach($driver->params as $identifier => $param) {
                    $key = sprintf('%s_%s', $palimpsest->driver, $identifier);
                    if ($request->has($key)) {
                        $config->$identifier = $request->input($key);
                    }
                    else {
                        $config->$identifier = '';
                    }
                }

                break;
            }
        }

        $palimpsest->config = json_encode($config);
        return $palimpsest;
    }

    public function store(Request $request)
    {
        $p = new Palimpsest();
        $p->user_id = $request->user()->id;
        $p = $this->readRequest($p, $request);
        $p->save();
        return redirect()->route('palimpsest.index');
    }

    public function update(Request $request, Palimpsest $palimpsest)
    {
        $palimpsest = $this->readRequest($palimpsest, $request);
        $palimpsest->save();
        return redirect()->route('palimpsest.index');
    }

    public function record(Request $request, Palimpsest $palimpsest, $record)
    {
        $record = $palimpsest->records()->where('identifier', $record)->first();
        if ($record) {
            return view('palimpsest.record', compact('record', 'palimpsest'));
        }
    }

    public function handleRecords(Request $request, Palimpsest $palimpsest)
    {
        $user = $request->user();

        if ($request->has('identifier')) {
            $id = $request->input('identifier');
            $record = $palimpsest->records()->where('identifier', $id)->first();
            if ($record) {
                $record->readRequest($request);
                $palimpsest->records()->updateExistingPivot($record->id, ['notes' => $request->input('notes', '')]);
            }
        }
        else {
            $record = new Record();
            $record->identifier = (string) Str::uuid();
            $record->user_id = $user->id;

            $record->readRequest($request);
            $palimpsest->records()->attach([$record->id => ['notes' => $request->input('notes', ''), 'sorting' => $palimpsest->records()->count()]]);
        }
    }

    public function loopback(Request $request, Palimpsest $palimpsest, $record_identifier, $status)
    {
        $record = $palimpsest->records()->where('identifier', $record_identifier)->first();
        if ($record) {
            $record->loopback($status == '1');
            return view('record.cell', compact('record'));
        }
    }

    public function broadcast(Request $request, Palimpsest $palimpsest, $record_identifier)
    {
        $record = $palimpsest->records()->where('identifier', $record_identifier)->first();
        if ($record) {
            $palimpsest->broadcast($record);
            return view('record.cell', compact('record'));
        }
    }

    public function askRemove(Request $request, Palimpsest $palimpsest)
    {
        $user = $request->user();
        return view('palimpsest.askremove', compact('palimpsest', 'user'));
    }

    public function destroy(Palimpsest $palimpsest)
    {
        $palimpsest->delete();
        return redirect()->route('palimpsest.index');
    }
}

resources/views/palimpsest/askremove.blade.php
<div class="modal fade" id="remove-palimpsest-{{ $palimpsest->id }}" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Palimpsest</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ route('palimpsest.destroy', $palimpsest->id) }}">
                @csrf
                @method('DELETE')

                <div class="modal-body">
                    <p>
                        Are you sure to remove this palimpsest and all included records?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/palimpsest/edit.blade.php
<div class="modal fade" id="edit-palimpsest-{{ $palimpsest ? $palimpsest->id : 'new' }}" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Palimpsest</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ $palimpsest ? route('palimpsest.update', $palimpsest->id) : route('palimpsest.store') }}">
                @csrf

                @if($palimpsest)
                    @method('PUT')
                @endif

                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $palimpsest ? $palimpsest->name : '' }}">
                    </div>
                    <div class="form-group">
                        <label for="setup">Driver</label>
                        <select class="form-control" name="driver" required>
                            <option value="">Choose one</option>
                            @foreach(App\Destination::drivers() as $driver)
                                <option value="{{ $driver->identifier }}" {{ $palimpsest && $palimpsest->driver == $driver->identifier ? 'selected' : '' }}>{{ $driver->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    @foreach(App\Destination::drivers() as $driver)
                        <div class="params_block params_block_{{ $driver->identifier }} {{ $palimpsest && $palimpsest->driver == $driver->identifier ? '' : 'hidden' }}">
                            @foreach($driver->params as $identifier => $param)
                                <div class="form-group">
                                    <label for="config">{{ $param->label }}</label>
                                    <input type="text" class="form-control" id="{{ $driver->identifier }}_{{ $identifier }}" name="{{ $driver->identifier }}_{{ $identifier }}" value="{{ $palimpsest ? $palimpsest->subConfig($identifier) : '' }}">
                                </div>
                            @endforeach
                        </div>
                    @endforeach
                </div>
                <div class="modal-footer">
                    @if($palimpsest)
                        <a href="#" class="btn btn-danger remote-modal" data-modal-url="{{ route('palimpsest.ask_remove', $palimpsest->id) }}">Delete</a>
                    @endif

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/palimpsest/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row mb-5">
        <div class="col-md-12">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#edit-palimpsest-new">Create New Palimpsest</a>
            @include('palimpsest.edit', ['palimpsest' => null])

            <a href="{{ route('home') }}" class="btn btn-secondary">Go to Records List</a>
        </div>
    </div>
    <div class="row">
        @foreach($user->palimpsests as $palimpsest)
            <div class="col-md-3">
                <div class="card" data-palimpsest-id="{{ $palimpsest->id }}">
                    <div class="card-header">
                        <span class="float-right">
                            <a href="#" class="btn btn-primary add-to-palimpsest" data-toggle="modal" data-target="#edit-palimpsest-{{ $palimpsest->id }}-record-new">
                                <i class="icofont icofont-plus-square"></i>
                            </a>
                            @include('palimpsest.record', ['palimpsest' => $palimpsest, 'record' => null])

                            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#edit-palimpsest-{{ $palimpsest->id }}">
                                <i class="icofont icofont-gear"></i>
                            </a>
                            @include('palimpsest.edit', ['palimpsest' => $palimpsest])
                        </span>
                        {{ $palimpsest->name }}

                        <br>
                        <br>

                        <video autoplay controls id="loopback-palimpsest-{{ $palimpsest->id }}" class="video-js">
                            <source src="{{ $palimpsest->subConfig('readfrom') }}" type="application/x-mpegURL">
                        </video>
                    </div>

                    <div class="card-body">
                        @if($palimpsest->records()->count() == 0)
                            <div class="alert alert-info">
                                There are no records.
                            </div>
                        @else
                            @foreach($palimpsest->records as $record)
                                @include('record.cell', ['record' => $record])
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</div>

@endsection

resources/views/palimpsest/record.blade.php
<div class="modal fade" id="edit-palimpsest-{{ $palimpsest->id }}-record-{{ $record ? $record->id : 'new' }}" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Record</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ route('palimpsest.records', [$palimpsest->id]) }}" class="reload_on_submit">
                @csrf

                @if($record)
                    <input type="hidden" name="identifier" value="{{ $record->identifier }}">
                @endif

                <div class="modal-body">
                    <div class="form-group">
                        <label for="url">URL</label>
                        <input type="text" class="form-control" id="url" name="url" value="{{ $record ? $record->url : '' }}">
                    </div>
                    <div class="form-group">
                        <label for="setup">Initial Setup</label>
                        <textarea class="form-control" id="setup" name="setup">{{ $record ? $record->setup : '' }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="notes">Notes</label>
                        <textarea class="form-control" id="notes" name="notes">{{ $record ? $record->setup : '' }}</textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>