routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('css/{filename}', 'AssetsController@css')->where('filename', '(.*)')->name('assets.css');
Route::get('js/{filename}', 'AssetsController@js')->where('filename', '(.*)')->name('assets.js');
Route::get('fonts/{filename}', 'AssetsController@fonts')->where('filename', '(.*)')->name('assets.fonts');

Route::middleware('auth')->group(function() {
    Route::get('home', 'HomeController@index')->name('home');

    Route::get('palimpsest/record/{palimpsest}/{record}', 'PalimpsestController@record')->name('palimpsest.record');
    Route::post('palimpsest/records/{palimpsest}', 'PalimpsestController@handleRecords')->name('palimpsest.records');
    Route::post('palimpsest/loopback/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@loopback')->name('palimpsest.loopback');
    Route::post('palimpsest/broadcast/{palimpsest}/{record_identifier}/{status}', 'PalimpsestController@broadcast')->name('palimpsest.broadcast');
    Route::get('palimpsest/askremove/{palimpsest}', 'PalimpsestController@askRemove')->name('palimpsest.ask_remove');

    Route::get('record/askremove/{record:identifier}', 'RecordController@askRemove')->name('record.ask_remove');

    Route::resource('record', 'RecordController');
    Route::resource('palimpsest', 'PalimpsestController');
});

app/Record.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

use App;
use Log;

use App\Helpers\Loopback;

class Record extends Model
{
    public function destinations()
    {
        return $this->hasMany('App\Destination');
    }

    public function palimpsest()
    {
        return $this->belongsToMany('App\Palimpsest');
    }

    public function getLoopbackUrlAttribute()
    {
        if ($this->status == 'running') {
            foreach($this->destinations as $dest) {
                if ($dest->driver == 'loopback') {
                    return Loopback::viewUrl($dest->config);
                }
            }
        }

        return null;
    }

    public function getIsBroadcastingAttribute()
    {
        return $this->destinations()->where(function($query) {
            $query->where('driver', '!=', 'loopback');
        })->count() != 0;
    }

    public function getStatusIconAttribute()
    {
        switch($this->status) {
            case 'idle':
                return 'icofont-pause';
            case 'running':
                return 'icofont-play-alt-1';
            case 'finished':
                return 'icofont-stop';
        }
    }

    public function triggerDestinations($filename)
    {
        /*
            TODO
        */
    }

    /*
        This has to be executed after Record's Destinations have been updated
    */
    public function reroute()
    {
        $queue = App::make('RecordsQueue');

        if ($this->status != 'running') {
            $queue->add($this);
        }
        else {
            if ($record->destinations()->count() == 0) {
                $queue->stop($this);
            }
            else {
                $queue->updateStream($this);
            }
        }
    }

    public function loopback($do)
    {
        $current_loopback_url = $this->loopback_url;
        if (($do == true && $current_loopback_url != null) || ($do == false && $current_loopback_url == null)) {
            return;
        }

        if ($do) {
            $loopback_destinations = $this->destinations()->where(function($query) {
                $query->where('driver', 'loopback');
            })->count();

            if ($loopback_destinations == 0) {
                $dest = new Destination();
                $dest->driver = 'loopback';
                $dest->config = Str::random(20);
                $dest->record_id = $this->id;
                $dest->save();
            }
        }
        else {
            foreach($this->destinations as $dest) {
                if ($dest->driver == 'loopback') {
                    $dest->delete();
                }
            }
        }

        $this->reroute();
    }

    public static function sanitizeSetup($string)
    {
        if (empty($string)) {
            return '';
        }

        $test = $string;

        $test = preg_replace('/[mousemove|click|sleep]*/', '', $test);
        $test = preg_replace('/ [\.0-9]*/', '', $test);
        if(empty($test)) {
            return $string;
        }
        else {
            Log::debug('Invalid remote command string: ' . $string);
            return '';
        }
    }

    public static function checkAuth($request, $id)
    {
        $record = Record::where('identifier', $id)->first();
        if (is_null($record)) {
            throw new \Exception('Record ID not found', 1);
        }

        $user = $request->user();
        if (is_null($user)) {
            $user = User::where('api_key', $request->input('api_key'))->first();
            if (is_null($user)) {
                throw new \Exception('Unauthorized', 1);
            }
        }

        if ($record->user_id != $user->id) {
            throw new \Exception('Unauthorized', 1);
        }

        return $record;
    }

    public function readRequest($request)
    {
        $this->url = $request->input('url');
        $this->setup = self::sanitizeSetup($request->input('setup', ''));
        $this->status = 'idle';
        $this->save();

        $destinations = $request->input('destinations', []);
        $this->destinations()->delete();

        foreach($destinations as $destination) {
            $destination = json_decode($destination);
            $dest = new Destination();
            $dest->driver = $destination->driver;
            $dest->config = $destination->config;
            $dest->record_id = $this->id;
            $dest->save();
        }

        return $this;
    }
}

app/Http/Controllers/RecordController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App;
use DB;
use Log;

use App\User;
use App\Record;
use App\Destination;

class RecordController extends Controller
{
    private function getUser($request)
    {
        return User::where('api_key', $request->input('api_key'))->first()->id;
    }

    private function storeRecord(Request $request)
    {
        $validatedData = $request->validate([
            'api_key' => 'required|exists:users',
            'url' => 'required|url',
        ]);

        if ($request->has('identifier')) {
            $id = $request->input('identifier');
            $record = Record::checkAuth($request, $id);
        }
        else {
            $record = new Record();
            $record->identifier = (string) Str::uuid();
            $record->user_id = $this->getUser($request);
        }

        $record->readRequest($request);

        return $record;
    }

    public function init(Request $request)
    {
        try {
            DB::beginTransaction();
            $record = $this->storeRecord($request);
            DB::commit();

            return response()->json([
                'status' => 'ok',
                'id' => $record->identifier,
            ]);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }
    }

    public function start(Request $request)
    {
        try {
            DB::beginTransaction();

            $record = $this->storeRecord($request);

            $queue = App::make('RecordsQueue');
            $queue->add($record);

            DB::commit();

            return response()->json([
                'status' => 'ok',
                'id' => $record->identifier,
            ]);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }
    }

    public function act(Request $request, $id)
    {
        $validatedData = $request->validate([
            'api_key' => 'required|exists:users',
        ]);

        try {
            $record = Record::checkAuth($request, $id);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

        $queue = App::make('RecordsQueue');
        $command = Record::sanitizeSetup($request->input('command', ''));

        if (!empty($command)) {
            $queue->act($record, $command);
        }

        return response()->json([
            'status' => 'ok',
            'id' => $record->identifier,
        ]);
    }

    public function stop(Request $request, $id)
    {
        $validatedData = $request->validate([
            'api_key' => 'required|exists:users',
        ]);

        try {
            $record = Record::checkAuth($request, $id);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

        DB::beginTransaction();

        $queue = App::make('RecordsQueue');
        $queue->stop($record);

        DB::commit();

        return response()->json([
            'status' => 'ok',
            'id' => $record->identifier,
        ]);
    }

    public function delete(Request $request, $id)
    {
        try {
            $record = Record::checkAuth($request, $id);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

        $queue = App::make('RecordsQueue');
        $queue->stop($record);

        $record->delete();

        return response()->json([
            'status' => 'ok',
            'id' => $record->identifier,
        ]);
    }

    public function askRemove(Request $request, Record $record)
    {
        try {
            $record = Record::checkAuth($request, $record->identifier);
        }
        catch(\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

        $user = $request->user();
        return view('record.askremove', compact('record', 'user'));
    }
}

resources/views/record/askremove.blade.php
<div class="modal fade" id="remove-record-{{ $record->id }}" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Record</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form method="DELETE" action="{{ route('record.delete', $record->identifier) }}" class="reload_on_submit">
                <input type="hidden" name="api_key" value="{{ $user->api_key }}">

                <div class="modal-body">
                    <p>
                        Are you sure to remove this record?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/record/cell.blade.php
<div class="card mb-2" data-record-id="{{ $record->identifier }}">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a class="nav-link remote-modal" href="#" data-modal-url="{{ route('palimpsest.record', ['palimpsest' => $record->palimpsest->first()->id, 'record' => $record->identifier]) }}">
                    <i class="icofont icofont-gear"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link remote-modal" href="#" data-modal-url="{{ route('record.ask_remove', $record->identifier) }}">
                    <i class="icofont icofont-minus-square"></i>
                </a>
            </li>
        </ul>
    </div>

    @if($record->loopback_url)
        <video autoplay controls id="loopback-record-{{ $record->id }}" class="video-js">
            <source src="{{ $record->loopback_url }}" type="application/x-mpegURL">
        </video>
    @else
        <div class="record-card-status">
            <i class="icofont {{ $record->status_icon }}"></i>
        </div>
    @endif

    <div class="card-body">
        <p class="card-text">
            {{ $record->url }}<br>
            {{ $record->pivot->notes ?: 'No notes' }}
        </p>

        <button type="button" class="btn btn-warning {{ $record->loopback_url ? 'active' : '' }} do_loopback" data-toggle="button" aria-pressed="{{ $record->loopback_url ? 'true' : 'false' }}">
            Loopback
        </button>

        <button type="button" class="btn btn-primary {{ $record->is_broadcasting ? 'active' : '' }} do_broadcast" data-toggle="button" aria-pressed="{{ $record->loopback_url ? 'true' : 'false' }}">
            Broadcast
        </button>
    </div>
</div>

resources/views/record/edit.blade.php
<div class="modal fade" id="edit-record-{{ $record ? $record->id : 'new' }}" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Record</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form method="GET" action="{{ route('record.init') }}" class="reload_on_submit">
                <input type="hidden" name="api_key" value="{{ $user->api_key }}">

                @if($record)
                    <input type="hidden" name="identifier" value="{{ $record->identifier }}">
                @endif

                <div class="modal-body">
                    <div class="form-group">
                        <label for="url">URL</label>
                        <input type="text" class="form-control" id="url" name="url" value="{{ $record ? $record->url : '' }}">
                    </div>
                    <div class="form-group">
                        <label for="setup">Initial Setup</label>
                        <textarea class="form-control" id="setup" name="setup">{{ $record ? $record->setup : '' }}</textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>